---
title: "Untitled"
author: "Matte"
date: '2019-06-19'
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
library(tidyverse)
library(praise)
praise()
library(janitor)
library(stringr)
install.packages("stringr")
library(stringr)
library(skimr)

## data filepaths/urls ----

## benthic data
benthic_url <- 'https://www.nodc.noaa.gov/archive/arc0054/0104255/1.1/data/0-data/cd08/100308OaAla03m.CSV'

## buoy data
buoy_url <- 'http://www.ndbc.noaa.gov/view_text_file.php?filename=mokh1h2010.txt.gz&dir=data/historical/stdmet/'



```

#Read benthic data

```{r benthic raw}
benthic_raw<-read.csv(benthic_url)
head(benthic_raw)


```

#Wrangle
```{r wrangle!}
benthic<-benthic_raw %>% 
  janitor::clean_names()

#explore
head(benthic)
names(benthic)


#select columns

benthic<-benthic %>% 
  select(id_name, point, x, y, id_date) %>%  
  mutate(date = stringr::str_remove_all(id_date, "#"))

#Above is fucked


```

#Explore

```{r explore}
summary(benthic)
skimr::skim(benthic)

ggplot(benthic, aes(date, fill = id_name))+geom_bar()

## uninstall packages
remove.packages('tidyverse')
remove.packages('stringi')
remove.packages('stringr')

## install individual packages
install.packages('readr')
install.packages('dplyr')
install.packages('tidyr')

ggplot(benthic, aes(date, fill=id_name)) +
  geom_bar()

buoy<-readr::read_csv(buoy_url)
head(buoy)

buoy_raw<-read_table2(buoy_url)
head(buoy)



```

#Wrangle2
```{r}
buoy<-buoy_raw
#overwrtite column names
names(buoy)<-str_c(
  names(buoy),
  buoy %>% filter(`#YY` == "#yr"),
  sep = "_")

#looks better
names(buoy)

#Clean up #, and replace / with _
names(buoy) <- str_replace_all(names(buoy), "#", "")
names(buoy) <- str_replace_all(names(buoy), "/", "_")

names(buoy)

#Remove redundant first row
buoy <- buoy %>%
  filter(YY_yr != "#yr")

head(buoy)

buoy <- buoy %>%
  filter(YY_yr != "#yr")


```

#Explore

```{r}
ggplot(buoy, aes(WTMP_degC)) +
  geom_bar()


```

#Join
```{r}
head(benthic)
head(buoy)

#unite buoy dates
buoy<-buoy %>% 
  unite(date, c(YY_yr, MM_mo, DD_dy), sep = "-")

head(buoy)

#leftjoin benthic by date
bb_join<-benthic %>% 
  left_join(buoy, by = "date")

bb_join %>% 
  select(id_name, x, y, date, hh_hr, mm_mn, WTMP_degC) %>% 
  head()

```


